config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "pre_exes#index"
  devise_for :aprobadors
  # Routes for the Aprobador resource:

  # READ
  get("/aprobadors", { :controller => "aprobadors", :action => "index" })
  get("/aprobadors/:id_to_display", { :controller => "aprobadors", :action => "show" })

  #------------------------------

  devise_for :creadors
  # Routes for the Creador resource:

  # READ
  get("/creadors", { :controller => "creadors", :action => "index" })
  get("/creadors/:id_to_display", { :controller => "creadors", :action => "show" })

  #------------------------------

  # Routes for the Molde resource:

  # CREATE
  get("/moldes/new", { :controller => "moldes", :action => "new_form" })
  post("/create_molde", { :controller => "moldes", :action => "create_row" })

  # READ
  get("/moldes", { :controller => "moldes", :action => "index" })
  get("/moldes/:id_to_display", { :controller => "moldes", :action => "show" })

  # UPDATE
  get("/moldes/:prefill_with_id/edit", { :controller => "moldes", :action => "edit_form" })
  post("/update_molde/:id_to_modify", { :controller => "moldes", :action => "update_row" })

  # DELETE
  get("/delete_molde/:id_to_remove", { :controller => "moldes", :action => "destroy_row" })

  #------------------------------

  # Routes for the Eje resource:

  # CREATE
  get("/ejes/new", { :controller => "ejes", :action => "new_form" })
  post("/create_eje", { :controller => "ejes", :action => "create_row" })

  # READ
  get("/ejes", { :controller => "ejes", :action => "index" })
  get("/ejes/:id_to_display", { :controller => "ejes", :action => "show" })

  # UPDATE
  get("/ejes/:prefill_with_id/edit", { :controller => "ejes", :action => "edit_form" })
  post("/update_eje/:id_to_modify", { :controller => "ejes", :action => "update_row" })

  # DELETE
  get("/delete_eje/:id_to_remove", { :controller => "ejes", :action => "destroy_row" })

  #------------------------------

  # Routes for the Ejercicio resource:

  # CREATE
  get("/ejercicios/new", { :controller => "ejercicios", :action => "new_form" })
  post("/create_ejercicio", { :controller => "ejercicios", :action => "create_row" })
  post("/create_ejercicio_from_molde", { :controller => "ejercicios", :action => "create_row_from_molde" })
  post("/create_ejercicio_from_contentido", { :controller => "ejercicios", :action => "create_row_from_contentido" })
  post("/create_ejercicio_from_pre_ex", { :controller => "ejercicios", :action => "create_row_from_pre_ex" })

  # READ
  get("/ejercicios", { :controller => "ejercicios", :action => "index" })
  get("/ejercicios/:id_to_display", { :controller => "ejercicios", :action => "show" })

  # UPDATE
  get("/ejercicios/:prefill_with_id/edit", { :controller => "ejercicios", :action => "edit_form" })
  post("/update_ejercicio/:id_to_modify", { :controller => "ejercicios", :action => "update_row" })

  # DELETE
  get("/delete_ejercicio/:id_to_remove", { :controller => "ejercicios", :action => "destroy_row" })
  get("/delete_ejercicio_from_aprobador/:id_to_remove", { :controller => "ejercicios", :action => "destroy_row_from_aprobador" })
  get("/delete_ejercicio_from_creador/:id_to_remove", { :controller => "ejercicios", :action => "destroy_row_from_creador" })
  get("/delete_ejercicio_from_molde/:id_to_remove", { :controller => "ejercicios", :action => "destroy_row_from_molde" })
  get("/delete_ejercicio_from_contenido/:id_to_remove", { :controller => "ejercicios", :action => "destroy_row_from_contenido" })
  get("/delete_ejercicio_from_last_pre_ex/:id_to_remove", { :controller => "ejercicios", :action => "destroy_row_from_last_pre_ex" })

  #------------------------------

  # Routes for the Contentido resource:

  # CREATE
  get("/contentidos/new", { :controller => "contentidos", :action => "new_form" })
  post("/create_contentido", { :controller => "contentidos", :action => "create_row" })
  post("/create_contentido_from_eje", { :controller => "contentidos", :action => "create_row_from_eje" })

  # READ
  get("/contentidos", { :controller => "contentidos", :action => "index" })
  get("/contentidos/:id_to_display", { :controller => "contentidos", :action => "show" })

  # UPDATE
  get("/contentidos/:prefill_with_id/edit", { :controller => "contentidos", :action => "edit_form" })
  post("/update_contentido/:id_to_modify", { :controller => "contentidos", :action => "update_row" })

  # DELETE
  get("/delete_contentido/:id_to_remove", { :controller => "contentidos", :action => "destroy_row" })
  get("/delete_contentido_from_eje/:id_to_remove", { :controller => "contentidos", :action => "destroy_row_from_eje" })

  #------------------------------

  # Routes for the Pre ex resource:

  # CREATE
  get("/pre_exes/new", { :controller => "pre_exes", :action => "new_form" })
  post("/create_pre_ex", { :controller => "pre_exes", :action => "create_row" })
  post("/create_pre_ex_from_molde", { :controller => "pre_exes", :action => "create_row_from_molde" })
  post("/create_pre_ex_from_contentido", { :controller => "pre_exes", :action => "create_row_from_contentido" })

  # READ
  get("/pre_exes", { :controller => "pre_exes", :action => "index" })
  get("/pre_exes/:id_to_display", { :controller => "pre_exes", :action => "show" })

  # UPDATE
  get("/pre_exes/:prefill_with_id/edit", { :controller => "pre_exes", :action => "edit_form" })
  post("/update_pre_ex/:id_to_modify", { :controller => "pre_exes", :action => "update_row" })

  # DELETE
  get("/delete_pre_ex/:id_to_remove", { :controller => "pre_exes", :action => "destroy_row" })
  get("/delete_pre_ex_from_molde/:id_to_remove", { :controller => "pre_exes", :action => "destroy_row_from_molde" })
  get("/delete_pre_ex_from_contenido/:id_to_remove", { :controller => "pre_exes", :action => "destroy_row_from_contenido" })

  #------------------------------

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_bootstrapcdn_assets.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" >

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

app/views/shared/_flashes.html.erb
<div class="row">
  <div class="col-md-12">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissable" role="alert">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissable" role="alert">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">
      PortalCarga
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible-nav-links" aria-controls="collapsible-nav-links" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsible-nav-links">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a href="/aprobadors" class="dropdown-item">
              Aprobadors
            </a>
            <a href="/creadors" class="dropdown-item">
              Creadors
            </a>
            <a href="/moldes" class="dropdown-item">
              Moldes
            </a>
            <a href="/ejes" class="dropdown-item">
              Ejes
            </a>
            <a href="/ejercicios" class="dropdown-item">
              Ejercicios
            </a>
            <a href="/contentidos" class="dropdown-item">
              Contentidos
            </a>
            <a href="/pre_exes" class="dropdown-item">
              Pre Exes
            </a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_aprobador.blank? %>
          <li class="nav-item">
            <a href="/aprobadors/sign_in" class="nav-link">
              Aprobador sign in
            </a>
          </li>

          <li class="nav-item">
            <a href="/aprobadors/sign_up" class="nav-link">
              Aprobador sign up
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/aprobadors/edit" class="nav-link">
              Aprobador edit profile
            </a>
          </li>

          <li class="nav-item">
            <a href="/aprobadors/sign_out" data-method="delete" class="nav-link">
              Aprobador sign out
            </a>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if current_creador.blank? %>
          <li class="nav-item">
            <a href="/creadors/sign_in" class="nav-link">
              Creador sign in
            </a>
          </li>

          <li class="nav-item">
            <a href="/creadors/sign_up" class="nav-link">
              Creador sign up
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/creadors/edit" class="nav-link">
              Creador edit profile
            </a>
          </li>

          <li class="nav-item">
            <a href="/creadors/sign_out" data-method="delete" class="nav-link">
              Creador sign out
            </a>
          </li>
        <% end %>
      </ul>
</nav>